const express=require('express')
const mongoose=require('mongoose')
// const bodyparser=require('body-parser')
const router=require('./routes')
const logindiary=require('./loginroutes')
const cors=require('cors')
const logindoc=require('./logindoc')
const web=express()
web.use(cors())
//web.use(bodyparser.urlencoded({extended:true}))
web.use(express.json())
web.use(express.urlencoded({extend:true}))
web.use(router)
web.use(logindiary)
 web.use(logindoc)
mongoose.connect("mongodb://localhost:27017/create_account")
.then(()=>{
    console.log("mongodb connected")
})
.catch((err)=>{
    console.log(err)
})
web.listen((8000),()=>{
    console.log("server listening")
})
